# Site settings
name: Fandy Kuncoro
title: Fandy Kuncoro
description: Fandy Kuncoro's Portfolio
url: https://fandykun.github.io/
baseurl: ''
email: fandy.kuncoro@gmail.com
cover: https://fandykun.github.io/img/og.png
logo: https://fandykun.github.io/img/close-up.png
icon: 
social:
  - title: email
    url: mailto:fandy.kuncoro@gmail.com
  - title: twitter
    url: https://twitter.com/fandykunnn
  - title: instagram
    url: https://instagram.com/fandykun
  - title: github
    url: https://github.com/fandykun
  - title: linkedin
    url: https://www.linkedin.com/in/fandy-kuncoro

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
